const time = new Date();
console.log(time);
const month = time.getMonth() + 1;
const day = time.getDate();
console.log(day);
const dayNum = time.getDay();
console.log(dayNum);
const hh = time.getHours();
const mm = time.getMinutes();
const sec = time.getSeconds();
const timeSinceTheSenventies = time.getTime();
const base = prompt("Enter the base of a Triangel", "Enter number here");
const hight = prompt("Enter hight of the triangel", "Enter number here");
const areaOfaTriangel = alert(0.5 * base * hight);
