console.log("python".length === "jargon".length);
console.log(4 > 3 && 10 < 12, "true");
console.log(4 > 3 && 10 > 12, "false");
console.log(4 > 3 || 10 < 12, "true");
console.log(4 > 3 || 10 > 12, "ture");
console.log(!(4 > 3), "false");
console.log(!(4 < 3), "ture");
console.log(!false, "ture");
console.log(!(4 > 3 && 10 < 12), "false");
console.log(!(4 > 3 && 10 > 12), "ture");
console.log(!(4 === "4"), "ture");
console.log(!("dragon".includes("on") && "python".includes("on")));
